services:
  scraper:
    build:
      context: .
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - ./volumes/redisdata:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge