services:
  scraper:
    build:
      context: .
    network_mode: host
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - ./volumes/redisdata:/data
    network_mode: host