services:
  squid:
    image: ubuntu/squid
    ports:
      - "3128:3128"
    volumes:
      - ./volumes/squid.conf:/etc/squid/squid.conf

  scraper:
    build:
      context: .
    depends_on:
      - squid
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - ./volumes/redisdata:/data\